# Generated by Django 4.2.22 on 2025-12-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screener", "0125_screen_has_head_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="has_early_head_start",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
